### ISSUE TITLE
Does the FindSourceFiles worked for binary file?

### ISSUE THREAD

**Issue by iamshowpune** [openrewrite/rewrite-cloud-suitability-analyzer#6]
For the recipe https://github.com/openrewrite/rewrite-cloud-suitability-analyzer/blob/a58580fd3be8fa520709417a0286ccbb087299db/src/main/resources/META-INF/rewrite/finders.yml#L314, I am not sure if it works, as it will throw exception like "The contents of a quark are unknown, so the charset is unknown" because the jks normally are binary files

**Comment by timtebeek** [comment]
Hi @iamshowpune; thank you for reporting this here! I've marked it as a bug; we might need to see about how we report markers on binary files, as indeed for binary files it might not work presently.

I quickly looked to see if I could replicate the exact message that you're getting by adapting [the unit test that we have for finding JKS files](https://github.com/openrewrite/rewrite-cloud-suitability-analyzer/blob/v1.2.0/src/test/java/org/openrewrite/cloudsuitability/FindUnsuitableCodeTest.java). When I adapt that to use `org.openrewrite.test.SourceSpecs.other` instead of `org.openrewrite.test.SourceSpecs.text` I get a slightly different error message:

```
[Unexpected result in "mykeystore.jks"] 
expected: "~~>contents do not matter"
 but was: "~~>⚛⚛⚛ The contents of this file are not visible. ⚛⚛⚛"
```

That's not much better; I think we should properly support binary files and guard that with a unit test.

**Comment by sambsnyd** [comment]
We don't have any way to display diffs of binary files, and therefore also do not have any way to render markers within them. Definitely something to be improved, but it isn't immediately obvious to me how best to go about it.

**Comment by timtebeek** [comment]
So if we're not able to present those search markers on Quarks, then that breaks [the existing FindJks recipe](https://github.com/openrewrite/rewrite-cloud-suitability-analyzer/blob/v1.3.0/src/main/resources/META-INF/rewrite/finders.yml#L305) right?
Any quick ways we can have that not throw an exception when run locally?

**Comment by sambsnyd** [comment]
Given their non-text nature we can't print anything inside a quark or binary. 
The console should still print a "Recipe would make changes to..." entry for quarks and binary, though. So you could look at that to see that such a file was found by a search recipe

**Comment by timtebeek** [comment]
Figured [this change](https://github.com/openrewrite/rewrite-maven-plugin/pull/517) would then close this issue; would you both agree? Or were you using Gradle @iamshowpune ?
